# Generated by Django 2.1.4 on 2019-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='device_reporting_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='device_reporting_frequency_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
