# Generated by Django 2.1.4 on 2019-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190327_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('key', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'individual_tracking',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='individualtracking',
            index=models.Index(fields=['imei'], name='individual__imei_3ec1c2_idx'),
        ),
    ]
