# Generated by Django 2.1.4 on 2019-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190402_1309'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='individualtracking',
            name='individual__imei_3ec1c2_idx',
        ),
        migrations.AlterField(
            model_name='individualtracking',
            name='key',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='individualtracking',
            index=models.Index(fields=['imei', 'key'], name='individual__imei_e3dc8c_idx'),
        ),
    ]
