# Generated by Django 2.1.4 on 2019-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190404_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='battery_low_limit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='sos_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='sos_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='sos_sms',
            field=models.BooleanField(default=True),
        ),
    ]
