# Generated by Django 2.1.4 on 2019-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190405_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='charging_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='charging_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='charging_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='power_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='power_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='power_sms',
            field=models.BooleanField(default=True),
        ),
    ]
