# Generated by Django 2.1.4 on 2019-04-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190405_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='battery_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='battery_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='battery_sms',
            field=models.BooleanField(default=False),
        ),
    ]
