# Generated by Django 2.1.4 on 2019-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190405_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='charging_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='power_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='sos_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
