# Generated by Django 2.1.4 on 2019-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190408_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_sms',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='charging_sms',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='sos_sms',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
