# Generated by Django 2.1.4 on 2019-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190408_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='power_sms',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
