# Generated by Django 2.1.4 on 2019-04-10 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190409_0640'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_imei_no_8afd09_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_no', 'customer_id', 'activated_plan_id', 'is_active', 'device_in_use', 'record_date'], name='subscriptio_imei_no_b5c136_idx'),
        ),
    ]
