# Generated by Django 2.1.4 on 2019-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190410_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='device_listing',
            field=models.BooleanField(default=True),
        ),
    ]
