# Generated by Django 2.1.4 on 2019-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_subscription_device_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='device_in_use',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='device_listing',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
