# Generated by Django 2.1.4 on 2019-04-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_settingsmodel_show_battery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsmodel',
            name='zone_alert_email',
        ),
        migrations.RemoveField(
            model_name='settingsmodel',
            name='zone_alert_sms',
        ),
    ]
