# Generated by Django 2.1.4 on 2019-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190424_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='trip_coordinate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='trip_sensor',
            field=models.BooleanField(default=True),
        ),
    ]
