# Generated by Django 2.1.4 on 2019-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190424_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='device_frequency_value',
            field=models.IntegerField(null=True),
        ),
    ]
