# Generated by Django 2.1.4 on 2019-04-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_settingsmodel_device_frequency_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticationsender',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
