# Generated by Django 2.1.4 on 2019-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_noticationsender_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_end_timer',
            field=models.IntegerField(default=10),
        ),
    ]
