# Generated by Django 2.1.4 on 2019-05-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190430_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripCalculationData',
        ),
        migrations.DeleteModel(
            name='TripCalculationGLData',
        ),
    ]
