# Generated by Django 2.1.4 on 2019-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190502_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='imei',
            field=models.CharField(max_length=25),
        ),
    ]
