# Generated by Django 2.1.4 on 2019-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190525_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='speed_limit',
            field=models.FloatField(default=80, null=True),
        ),
    ]
