# Generated by Django 2.1.4 on 2019-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190622_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='global_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='global_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='global_sms',
            field=models.BooleanField(default=True),
        ),
    ]
