# Generated by Django 2.1.4 on 2019-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190625_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='attach_dettach_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='attach_dettach_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='attach_dettach_sms',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
