# Generated by Django 2.1.4 on 2019-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190625_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_sms',
            field=models.BooleanField(default=False),
        ),
    ]
