# Generated by Django 2.1.4 on 2019-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190625_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_notification',
            field=models.BooleanField(default=False),
        ),
    ]
