# Generated by Django 2.1.4 on 2019-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190812_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('fuel_economy', models.FloatField(null=True)),
                ('record_date', models.DateField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'fuel_economy',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='fueleconomy',
            index=models.Index(fields=['imei', 'record_date', 'fuel_economy'], name='fuel_econom_imei_968eab_idx'),
        ),
    ]
