# Generated by Django 2.1.4 on 2019-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190813_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='attach_dettach_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='battery_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='charging_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='engine_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='harsh_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='power_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='sos_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='speed_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='tow_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='trip_notification_global',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='attach_dettach_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='attach_dettach_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='attach_dettach_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_low_limit',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='battery_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='charging_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='charging_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='charging_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='engine_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='engine_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='engine_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshacceleration_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshacceleration_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshacceleration_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshbraking_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshbraking_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshbraking_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshturning_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshturning_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='harshturning_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='power_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='power_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='power_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_battery',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_engine_load',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_engine_rpm',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_engine_temp',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_fuel_consumption',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_fuel_level',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_location',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_mileage',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_speed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_throttle_position',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='show_voltage',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='sos_email',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='sos_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='sos_sms',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='speed_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='speed_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='speed_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='tow_email',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='tow_notification',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='tow_sms',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_coordinate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_email',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_end_timer',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_notification',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_sensor',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='trip_sms',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='zone_alert_notification',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
