# Generated by Django 2.1.4 on 2019-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190814_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('driver_score', models.FloatField(null=True)),
                ('record_date', models.DateField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'driver_score',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='driverscore',
            index=models.Index(fields=['imei', 'record_date', 'driver_score'], name='driver_scor_imei_dad95a_idx'),
        ),
    ]
