# Generated by Django 2.1.4 on 2019-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190831_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='device_reporting_frequency_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
