# Generated by Django 2.1.4 on 2019-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190904_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverscore',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fueleconomy',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='harshbehaviourevent',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='odometere',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripevents',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voltagemodel',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
