# Generated by Django 2.1.4 on 2019-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190913_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('map_type', models.CharField(blank=True, default='standard', max_length=50, null=True)),
                ('traffic', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'map_settings',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='mapsettings',
            index=models.Index(fields=['customer_id'], name='map_setting_custome_3f13a0_idx'),
        ),
    ]
