# Generated by Django 2.1.4 on 2019-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190925_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='imei',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
