# Generated by Django 2.1.4 on 2019-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20191015_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtcEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=25)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('record_date', models.DateField(null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('dtc_code', models.CharField(blank=True, max_length=50)),
                ('dtc_short_description', models.TextField(null=True)),
                ('error_code_url', models.CharField(blank=True, max_length=500, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dtc_events',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='dtcevents',
            index=models.Index(fields=['imei', 'customer_id', 'record_date', 'dtc_code'], name='dtc_events_imei_9c408d_idx'),
        ),
    ]
