# Generated by Django 2.1.4 on 2019-10-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20191019_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcevents',
            name='record_time',
            field=models.TimeField(null=True),
        ),
    ]
