# Generated by Django 2.1.4 on 2019-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_dtcevents_record_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('protocol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'trip_end_record',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='tripendrecord',
            index=models.Index(fields=['imei', 'protocol'], name='trip_end_re_imei_2f1dd7_idx'),
        ),
    ]
