# Generated by Django 2.1.4 on 2019-10-31 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20191031_0551'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tripendrecord',
            name='trip_end_re_imei_2f1dd7_idx',
        ),
        migrations.AddField(
            model_name='tripendrecord',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 31, 7, 49, 25, 947194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tripendrecord',
            index=models.Index(fields=['imei', 'protocol', 'record_date'], name='trip_end_re_imei_07fc3d_idx'),
        ),
    ]
