# Generated by Django 2.1.4 on 2019-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20191031_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='routes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zones',
            name='routes_tuple',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zones',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
