# Generated by Django 2.1.4 on 2019-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20191105_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonealert',
            name='category',
            field=models.CharField(default='gps', max_length=20),
            preserve_default=False,
        ),
    ]
