# Generated by Django 2.1.4 on 2019-11-07 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20191105_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueleconomy',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
