# Generated by Django 2.1.4 on 2019-11-08 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20191107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueleconomy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fueleconomy',
            name='record_date',
            field=models.DateField(null=True),
        ),
    ]
