# Generated by Django 2.1.4 on 2019-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20191108_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('emission', models.FloatField(null=True)),
                ('record_date', models.DateField(null=True)),
                ('customer_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emission',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='emission',
            index=models.Index(fields=['imei', 'record_date', 'emission', 'customer_id'], name='emission_imei_f0f5b2_idx'),
        ),
    ]
