# Generated by Django 2.1.4 on 2019-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20191113_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('next_review_date', models.DateField(null=True)),
                ('eligible', models.BooleanField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'review_table',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='reviewtable',
            index=models.Index(fields=['customer_id'], name='review_tabl_custome_94a2ef_idx'),
        ),
    ]
