# Generated by Django 2.1.4 on 2019-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20191122_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtable',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
