# Generated by Django 2.1.4 on 2019-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_reviewtable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='mobile_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='secondary_mobile_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonealert',
            name='phone_one_mobile_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonealert',
            name='phone_two_mobile_carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
