# Generated by Django 2.1.4 on 2019-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20191126_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsEmailCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('email_count', models.IntegerField(null=True)),
                ('sms_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sms_email_count',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='smsemailcount',
            index=models.Index(fields=['customer_id'], name='sms_email_c_custome_f4d606_idx'),
        ),
    ]
