# Generated by Django 2.1.4 on 2019-12-04 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20191204_1142'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smsemailcount',
            name='sms_email_c_custome_f4d606_idx',
        ),
        migrations.AddField(
            model_name='smsemailcount',
            name='record_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='smsemailcount',
            index=models.Index(fields=['customer_id', 'record_date'], name='sms_email_c_custome_3e7c6a_idx'),
        ),
    ]
