# Generated by Django 2.1.4 on 2020-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20191204_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='fuel_capacity',
            field=models.FloatField(null=True),
        ),
    ]
