# Generated by Django 2.1.4 on 2020-01-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_settingsmodel_fuel_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneAlertObd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.CharField(max_length=50)),
                ('email_one', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_one_mobile_carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('email_two', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_two_mobile_carrier', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'zone_alert_obd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZoneObd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'zone_obd',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='zoneobd',
            index=models.Index(fields=['customer_id', 'created_on', 'name', 'type'], name='zone_obd_custome_9b529d_idx'),
        ),
        migrations.AddField(
            model_name='zonealertobd',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_alert_obd', to='app.ZoneObd'),
        ),
        migrations.AddIndex(
            model_name='zonealertobd',
            index=models.Index(fields=['customer_id', 'created_on', 'name', 'imei', 'type', 'zone'], name='zone_alert__custome_66ed52_idx'),
        ),
    ]
