# Generated by Django 2.1.4 on 2020-02-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_freetrialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='device_frequency_value',
            field=models.FloatField(null=True),
        ),
    ]
