# Generated by Django 2.1.4 on 2020-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20200214_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='global_sms',
            field=models.BooleanField(default=True),
        ),
    ]
