# Generated by Django 2.1.4 on 2020-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20200407_1146'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelconsumption',
            index=models.Index(fields=['imei', 'record_date', 'consumption', 'customer_id'], name='fuel_consum_imei_445f94_idx'),
        ),
    ]
