# Generated by Django 2.1.4 on 2020-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20200407_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsIdealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('ideal_time', models.CharField(max_length=5)),
                ('from_send_time', models.CharField(max_length=30)),
                ('to_send_time', models.CharField(max_length=30)),
                ('start_record', models.TextField(blank=True, null=True)),
                ('end_record', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gps_ideal_time',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='gpsidealtime',
            index=models.Index(fields=['imei'], name='gps_ideal_t_imei_a564c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsidealtime',
            index=models.Index(fields=['imei', 'created_on'], name='gps_ideal_t_imei_208af5_idx'),
        ),
    ]
