# Generated by Django 2.1.4 on 2020-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20201201_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsidealtime',
            name='record_date_timezone',
            field=models.DateField(null=True),
        ),
        migrations.AddIndex(
            model_name='gpsidealtime',
            index=models.Index(fields=['imei', 'record_date_timezone'], name='gps_ideal_t_imei_2327e1_idx'),
        ),
    ]
