# Generated by Django 2.1.4 on 2020-12-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20201202_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryDrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=10)),
                ('time_spent', models.CharField(max_length=10)),
                ('battery', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'battery_train',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei'], name='battery_tra_imei_a1e75c_idx'),
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei', 'created_on'], name='battery_tra_imei_338c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei', 'date'], name='battery_tra_imei_d6670a_idx'),
        ),
    ]
