# Generated by Django 2.1.4 on 2020-12-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20201225_1517'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batterydrain',
            name='battery_tra_imei_a1e75c_idx',
        ),
        migrations.RemoveIndex(
            model_name='batterydrain',
            name='battery_tra_imei_338c0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='batterydrain',
            name='battery_tra_imei_d6670a_idx',
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei'], name='battery_dra_imei_a8fc75_idx'),
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei', 'created_on'], name='battery_dra_imei_44c4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='batterydrain',
            index=models.Index(fields=['imei', 'date'], name='battery_dra_imei_c5811c_idx'),
        ),
        migrations.AlterModelTable(
            name='batterydrain',
            table='battery_drain',
        ),
    ]
