# Generated by Django 2.1.4 on 2021-04-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20201225_1528'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_no', 'sim_status'], name='subscriptio_imei_no_3074b0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_no', 'customer_id'], name='subscriptio_imei_no_5c48e2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_no'], name='subscriptio_imei_no_072caa_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_iccid'], name='subscriptio_imei_ic_3c6378_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['imei_no', 'device_listing', 'customer_id'], name='subscriptio_imei_no_eb4484_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['device_model', 'device_listing', 'customer_id', 'device_in_use'], name='subscriptio_device__4d333e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active', 'customer_id'], name='subscriptio_is_acti_32355c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer_id'], name='subscriptio_custome_e8e295_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_id'], name='subscriptio_subscri_fda933_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealert',
            index=models.Index(fields=['customer_id'], name='zone_alert_custome_f0d87c_idx'),
        ),
        migrations.AddIndex(
            model_name='zonegroup',
            index=models.Index(fields=['created_by'], name='zone_group_created_88e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='zones',
            index=models.Index(fields=['customer_id'], name='zones_custome_a3eba6_idx'),
        ),
    ]
