# Generated by Django 2.1.4 on 2021-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20210428_1040'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settingsmodel',
            index=models.Index(fields=['imei'], name='settings_imei_80b80a_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealertobd',
            index=models.Index(fields=['customer_id', 'zone'], name='zone_alert__custome_3d5882_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealertobd',
            index=models.Index(fields=['zone'], name='zone_alert__zone_id_4981b6_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealertobd',
            index=models.Index(fields=['customer_id'], name='zone_alert__custome_c8ba33_idx'),
        ),
    ]
