# Generated by Django 2.1.4 on 2021-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20210428_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLevelTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('start_mileage', models.FloatField(null=True)),
                ('start_fuel_level', models.FloatField(null=True)),
                ('end_mileage', models.FloatField(null=True)),
                ('end_fuel_level', models.FloatField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fuel_level_tracker',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='fuelleveltracker',
            index=models.Index(fields=['imei'], name='fuel_level__imei_9ba575_idx'),
        ),
    ]
