# Generated by Django 2.1.4 on 2021-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_auto_20210609_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelleveltracker',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='fuel_capacity_unit',
            field=models.CharField(default='gallon', max_length=20),
        ),
    ]
