# Generated by Django 2.1.4 on 2021-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20210614_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBDDtcEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=25)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('record_date', models.DateField(null=True)),
                ('record_time', models.TimeField(null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('warning_code', models.CharField(blank=True, max_length=40, null=True)),
                ('warning_value', models.CharField(blank=True, max_length=40, null=True)),
                ('warning_details', models.CharField(blank=True, max_length=240, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'obd_dtc_events',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='warning_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='warning_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='warning_notification_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='warning_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='obddtcevents',
            index=models.Index(fields=['imei', 'customer_id', 'record_date', 'warning_code'], name='obd_dtc_eve_imei_09526e_idx'),
        ),
    ]
