# Generated by Django 3.2.11 on 2022-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20210618_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObdTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
