# Generated by Django 3.2.11 on 2022-01-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_userobdtrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserObdTrip',
        ),
    ]
