version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/amcrest_gps_pro
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install
      timeout: 300
  ApplicationStart:
    - location: deploy/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: root
