#!/bin/sh
. /home/ubuntu/env/bin/activate
pip install -r /home/ubuntu/amcrest_gps_pro/requirements.txt
python /home/ubuntu/amcrest_gps_pro/manage.py migrate
python /home/ubuntu/amcrest_gps_pro/manage.py migrate --database=listener_db
screen -d -m python /home/ubuntu/amcrest_gps_pro/manage.py runserver 0.0.0.0:8000
cd /home/ubuntu/amcrest_gps_pro
screen -d -m daphne -b 0.0.0.0 -p 8001 amcrest.asgi:application
