# Generated by Django 2.1.4 on 2019-03-08 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(blank=True, max_length=500, null=True, verbose_name='Username')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Password')),
                ('order_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Order ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='Zip')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('status', models.IntegerField(null=True, verbose_name='Status')),
                ('company', models.CharField(blank=True, max_length=30, null=True, verbose_name='Company')),
                ('customer_id', models.IntegerField(blank=True, null=True, verbose_name='Customer ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription ID')),
                ('transaction_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Transaction ID')),
                ('assetname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Asset Name')),
                ('subscription_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subscription Status')),
                ('topic_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Topic ID')),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time Zone')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Langauges')),
                ('uom', models.CharField(default='kms', max_length=10, null=True)),
                ('hits', models.FloatField(default=1, null=True, verbose_name='Hits')),
                ('rate', models.FloatField(default=9, null=True, verbose_name='Rate')),
                ('later_time', models.IntegerField(null=True, verbose_name='Later Time')),
                ('later_flag', models.IntegerField(default=1, null=True, verbose_name='Later Flag')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last Login')),
                ('first_login', models.DateTimeField(null=True, verbose_name='First Login')),
                ('login_count', models.IntegerField(null=True, verbose_name='Login Count')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cvv', models.IntegerField(null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=10, null=True)),
                ('start_number', models.CharField(blank=True, max_length=7, null=True)),
                ('end_number', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_card',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='creditcarddetails',
            index=models.Index(fields=['user'], name='credit_card_user_id_e1672b_idx'),
        ),
    ]
