# Generated by Django 2.1.4 on 2019-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Customer ID'),
        ),
    ]
