# Generated by Django 2.1.4 on 2019-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190419_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Time Zone Description'),
        ),
    ]
