# Generated by Django 2.1.4 on 2019-10-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191011_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dealer_relation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'username', 'customer_id'], name='user_user_email_5c8e5f_idx'),
        ),
        migrations.AddField(
            model_name='dealercustomers',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealercustomers',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dealercustomers',
            index=models.Index(fields=['dealer', 'customer'], name='dealer_rela_dealer__64a976_idx'),
        ),
    ]
