# Generated by Django 2.1.4 on 2019-10-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191021_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailing_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='Emailing Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dealer_user',
            field=models.BooleanField(default=False),
        ),
    ]
