# Generated by Django 2.1.4 on 2019-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191021_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_carrier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Carrier'),
        ),
    ]
