# Generated by Django 2.1.4 on 2020-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_mobile_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(default='24', max_length=10, verbose_name='Time Format'),
        ),
    ]
