# Generated by Django 2.1.4 on 2020-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_regenerate_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=30, verbose_name='Date Format'),
        ),
    ]
