# Generated by Django 2.1.4 on 2021-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subuser',
            field=models.BooleanField(default=False),
        ),
    ]
