# Generated by Django 2.1.4 on 2019-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_devicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmapping',
            name='provider',
            field=models.CharField(default='tele2', max_length=50),
            preserve_default=False,
        ),
    ]
