# Generated by Django 2.1.4 on 2019-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_simmapping_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='simupdatecredentials',
            name='key_name',
            field=models.CharField(default='tele2', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simupdatecredentials',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
