# Generated by Django 2.1.4 on 2019-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190316_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodSimCron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'pod_sim_cron',
                'managed': True,
            },
        ),
    ]
