# Generated by Django 2.1.4 on 2019-03-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_podsimcron'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmapping',
            name='customer_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simmapping',
            name='promotion_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
