# Generated by Django 2.1.4 on 2019-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190316_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimPlanUpdatedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sim_plan_update',
                'managed': True,
            },
        ),
    ]
