# Generated by Django 2.1.4 on 2019-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_simplanupdatedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_frequency', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'device_frequency',
                'managed': True,
            },
        ),
    ]
