# Generated by Django 2.1.4 on 2019-03-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_devicefrequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicefrequency',
            options={'managed': True, 'verbose_name': 'Device Frequency', 'verbose_name_plural': 'Device Frequency'},
        ),
        migrations.RenameField(
            model_name='devicefrequency',
            old_name='device_frequency',
            new_name='device_frequency_key',
        ),
        migrations.AddField(
            model_name='devicefrequency',
            name='device_frequency_value',
            field=models.CharField(default='60_sec', max_length=50),
            preserve_default=False,
        ),
    ]
