# Generated by Django 2.1.4 on 2019-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190405_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='protocol',
            field=models.CharField(max_length=15),
        ),
    ]
