# Generated by Django 2.1.4 on 2019-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190405_0738'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simmapping',
            name='sim_mapping_imei_f5d156_idx',
        ),
        migrations.AddField(
            model_name='simmapping',
            name='category',
            field=models.CharField(default='obd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='simmapping',
            index=models.Index(fields=['imei', 'model', 'duration_type', 'category'], name='sim_mapping_imei_3bb683_idx'),
        ),
    ]
