# Generated by Django 2.1.4 on 2019-04-11 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20190409_1140'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhooksubscription',
            name='webhook_log_webhook_0ffefd_idx',
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 11, 12, 31, 0, 986745, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['webhook_date_recieved', 'kind', 'subscription_id', 'record_date'], name='webhook_log_webhook_430dbd_idx'),
        ),
    ]
