# Generated by Django 2.1.4 on 2019-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_subscriptioncancelation_record_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceListingCron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'device_listing_cron',
                'managed': True,
            },
        ),
    ]
