# Generated by Django 2.1.4 on 2019-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_devicelistingcron'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timezonemodel',
            name='time_zones_time_zo_178a98_idx',
        ),
        migrations.RemoveField(
            model_name='timezonemodel',
            name='country_code',
        ),
        migrations.AddField(
            model_name='timezonemodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='timezonemodel',
            index=models.Index(fields=['time_zone'], name='time_zones_time_zo_619910_idx'),
        ),
    ]
