# Generated by Django 2.1.4 on 2019-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20190416_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefrequency',
            name='device_frequency',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
