# Generated by Django 2.1.4 on 2019-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_devicefrequency_device_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='key_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devicefrequency',
            name='device_frequency',
            field=models.FloatField(),
        ),
    ]
