# Generated by Django 2.1.4 on 2019-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20190523_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFrequencyObd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_frequency_key', models.CharField(max_length=20)),
                ('device_frequency_value', models.CharField(max_length=50)),
                ('device_frequency', models.FloatField()),
            ],
            options={
                'verbose_name': 'Device Frequency OBD',
                'verbose_name_plural': 'Device Frequency OBD',
                'db_table': 'device_frequency_obd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServicePlanObd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_plan_id', models.CharField(max_length=50)),
                ('service_plan_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ServicePlan',
                'verbose_name_plural': 'ServicePlans',
                'db_table': 'service_plan_obd',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='serviceplanobd',
            index=models.Index(fields=['service_plan_id'], name='service_pla_service_0796e7_idx'),
        ),
    ]
