# Generated by Django 2.1.4 on 2019-05-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190523_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplanobd',
            options={'managed': True, 'verbose_name': 'ServicePlanObd', 'verbose_name_plural': 'ServicePlansObd'},
        ),
    ]
