# Generated by Django 2.1.4 on 2019-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20190525_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmapping',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
