# Generated by Django 2.1.4 on 2019-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20191025_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_sent',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='reviewmodel',
            index=models.Index(fields=['customer_id', 'email'], name='review_sent_custome_5f2ba7_idx'),
        ),
    ]
