# Generated by Django 2.1.4 on 2019-11-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20191028_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_provider_name', models.CharField(max_length=200)),
                ('mobile_provider_domain', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mobile_service_providers',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='mobileserviceprovider',
            index=models.Index(fields=['mobile_provider_name'], name='mobile_serv_mobile__3b5a6e_idx'),
        ),
    ]
