# Generated by Django 2.1.4 on 2019-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_appversion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceplan',
            name='service_pla_service_b3fb1e_idx',
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='base_device_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['service_plan_id', 'base_device_frequency'], name='service_pla_service_613c00_idx'),
        ),
    ]
