# Generated by Django 2.1.4 on 2019-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20191203_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=200)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'imei_commands',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='key_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
