# Generated by Django 2.1.4 on 2020-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20200110_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=200)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('improve_software', models.TextField(blank=True, null=True)),
                ('missing_features', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'feedback_table',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='feedbackmodel',
            index=models.Index(fields=['rating', 'email'], name='feedback_ta_rating_91847c_idx'),
        ),
    ]
