# Generated by Django 2.1.4 on 2020-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20200113_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
