# Generated by Django 2.1.4 on 2020-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_feedbackmodel_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackSkipped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skipped_feedback',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='feedbackskipped',
            index=models.Index(fields=['email', 'created_date'], name='skipped_fee_email_6bc4f9_idx'),
        ),
    ]
