# Generated by Django 2.1.4 on 2020-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20200324_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='amazon_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
