# Generated by Django 2.1.4 on 2020-04-07 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_feedbackmodel_amazon_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommands',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
