# Generated by Django 2.1.4 on 2019-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30)),
                ('imei', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
