# Generated by Django 2.1.4 on 2019-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('report_name', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=8, null=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_accuracy', models.CharField(blank=True, max_length=2, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('azimuth', models.CharField(blank=True, max_length=4, null=True)),
                ('altitude', models.CharField(blank=True, max_length=8, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=20, null=True)),
                ('mcc', models.CharField(blank=True, max_length=4, null=True)),
                ('mnc', models.CharField(blank=True, max_length=4, null=True)),
                ('lac', models.CharField(blank=True, max_length=4, null=True)),
                ('ceil_id', models.CharField(blank=True, max_length=4, null=True)),
                ('odometer_mileage', models.FloatField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('tail', models.CharField(blank=True, max_length=5, null=True)),
                ('location_status', models.IntegerField(blank=True, null=True)),
                ('alert_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'battery_onoff',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('report_name', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=8, null=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('tail', models.CharField(blank=True, max_length=5, null=True)),
                ('alert_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'power_onoff',
            },
        ),
        migrations.CreateModel(
            name='SOS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('report_name', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=8, null=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('report_type', models.CharField(blank=True, max_length=2, null=True)),
                ('report_id', models.CharField(blank=True, max_length=2, null=True)),
                ('number', models.CharField(blank=True, max_length=3, null=True)),
                ('gps_accuracy', models.CharField(blank=True, max_length=3, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('azimuth', models.CharField(blank=True, max_length=4, null=True)),
                ('altitude', models.CharField(blank=True, max_length=8, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=20, null=True)),
                ('mcc', models.CharField(blank=True, max_length=4, null=True)),
                ('mnc', models.CharField(blank=True, max_length=4, null=True)),
                ('lac', models.CharField(blank=True, max_length=4, null=True)),
                ('ceil_id', models.CharField(blank=True, max_length=4, null=True)),
                ('odometer_mileage', models.FloatField(blank=True, null=True)),
                ('battery_percentage', models.CharField(blank=True, max_length=5, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('tail', models.CharField(blank=True, max_length=5, null=True)),
                ('alert_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sos_markers',
            },
        ),
        migrations.CreateModel(
            name='SttMarkers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('report_name', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=8, null=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.IntegerField(null=True)),
                ('gps_accuracy', models.CharField(blank=True, max_length=2, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('azimuth', models.CharField(blank=True, max_length=4, null=True)),
                ('altitude', models.CharField(blank=True, max_length=8, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=20, null=True)),
                ('mcc', models.CharField(blank=True, max_length=4, null=True)),
                ('mnc', models.CharField(blank=True, max_length=4, null=True)),
                ('lac', models.CharField(blank=True, max_length=4, null=True)),
                ('ceil_id', models.CharField(blank=True, max_length=4, null=True)),
                ('odometer_mileage', models.FloatField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('tail', models.CharField(blank=True, max_length=5, null=True)),
                ('location_status', models.IntegerField(blank=True, null=True)),
                ('alert_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stt_markers',
            },
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['date', 'imei', 'device_name', 'longitude', 'latitude', 'gps_utc_time', 'send_time'], name='stt_markers_date_f5f79c_idx'),
        ),
        migrations.AddIndex(
            model_name='sos',
            index=models.Index(fields=['date', 'imei', 'device_name', 'send_time', 'gps_utc_time', 'speed', 'longitude', 'latitude'], name='sos_markers_date_4846dd_idx'),
        ),
        migrations.AddIndex(
            model_name='power',
            index=models.Index(fields=['date', 'imei', 'device_name', 'send_time'], name='power_onoff_date_d67b98_idx'),
        ),
        migrations.AddIndex(
            model_name='batterymodel',
            index=models.Index(fields=['date', 'imei', 'device_name', 'longitude', 'latitude', 'gps_utc_time', 'send_time', 'gps_accuracy', 'speed'], name='battery_ono_date_ec6444_idx'),
        ),
    ]
