# Generated by Django 2.1.4 on 2019-04-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_auto_20190401_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sttmarkers',
            name='alert_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sttmarkers',
            name='location_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
