# Generated by Django 2.1.4 on 2019-04-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0006_glfrimarkers_report_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterymodel',
            old_name='odometer_mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='sos',
            old_name='odometer_mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='sttmarkers',
            old_name='odometer_mileage',
            new_name='mileage',
        ),
    ]
