# Generated by Django 2.1.4 on 2019-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0007_auto_20190404_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripProtocolRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'trip_protocol_recorder',
            },
        ),
        migrations.AddIndex(
            model_name='tripprotocolrecord',
            index=models.Index(fields=['imei', 'protocol'], name='trip_protoc_imei_b3857f_idx'),
        ),
    ]
