# Generated by Django 2.1.4 on 2019-05-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0009_auto_20190502_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripCalculationGLData',
        ),
    ]
