# Generated by Django 2.1.4 on 2019-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0011_auto_20190529_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuffGLFriMarkers',
        ),
        migrations.DeleteModel(
            name='BuffSttMarkers',
        ),
        migrations.AlterField(
            model_name='glfrimarkers',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sttmarkers',
            name='tail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
