# Generated by Django 2.1.4 on 2019-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0013_auto_20190529_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_send_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harshbehaviour',
            name='latest_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='altitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='instant_fuel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='speed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='air_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='cooling_fluid_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='duration_of_ignition_off',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='duration_of_ignition_on',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='instant_fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='over_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
