# Generated by Django 2.1.4 on 2019-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0014_auto_20190615_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitiononoff',
            name='alarm_code',
            field=models.IntegerField(null=True),
        ),
    ]
