# Generated by Django 2.1.4 on 2019-06-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0015_ignitiononoff_alarm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitiononoff',
            name='engine_coolant_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='external_battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='remain_fuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='throttle_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='data_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='digital_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='external_battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='remain_fuel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
