# Generated by Django 2.1.4 on 2019-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0016_auto_20190615_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obdmarkers',
            name='digital_status',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
