# Generated by Django 2.1.4 on 2019-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0017_auto_20190619_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitiononoff',
            name='air_inflow_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='air_input',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='air_inflow_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='air_input',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
