# Generated by Django 2.1.4 on 2019-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0018_auto_20190626_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=10, null=True)),
                ('imei', models.CharField(max_length=20)),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=15, null=True)),
                ('gps_accuracy', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=14, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('tail', models.CharField(blank=True, max_length=5, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('report_id', models.CharField(blank=True, max_length=5, null=True)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('azimuth', models.CharField(blank=True, max_length=5, null=True)),
                ('altitude', models.CharField(blank=True, max_length=10, null=True)),
                ('mcc', models.CharField(blank=True, max_length=5, null=True)),
                ('mnc', models.CharField(blank=True, max_length=5, null=True)),
                ('lac', models.CharField(blank=True, max_length=5, null=True)),
                ('ceil_id', models.CharField(blank=True, max_length=10, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'alert_records',
            },
        ),
        migrations.AddIndex(
            model_name='alertrecords',
            index=models.Index(fields=['date', 'imei', 'send_time', 'longitude', 'latitude', 'gps_accuracy', 'gps_utc_time', 'record_date'], name='alert_recor_date_8c06e1_idx'),
        ),
    ]
