# Generated by Django 2.1.4 on 2019-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0021_auto_20190819_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrecords',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batterymodel',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='glfrimarkers',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sos',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sttmarkers',
            name='ceil_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
