# Generated by Django 2.1.4 on 2019-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0022_auto_20190827_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=15, null=True)),
                ('imei', models.CharField(max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_of_ignition_off', models.CharField(blank=True, max_length=20, null=True)),
                ('gps_accuracy', models.CharField(blank=True, max_length=5, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=20, null=True)),
                ('hour_meter_count', models.CharField(blank=True, max_length=15, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('count_number', models.CharField(blank=True, max_length=5, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=10, null=True)),
                ('fuel_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('instant_fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('alarm_code', models.IntegerField(null=True)),
                ('external_battery', models.IntegerField(blank=True, null=True)),
                ('engine_coolant_temp', models.IntegerField(blank=True, null=True)),
                ('throttle_position', models.IntegerField(blank=True, null=True)),
                ('remain_fuel', models.IntegerField(blank=True, null=True)),
                ('air_input', models.FloatField(blank=True, null=True)),
                ('air_inflow_temperature', models.FloatField(blank=True, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'idle_time',
            },
        ),
        migrations.AddField(
            model_name='alertrecords',
            name='alarm_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='idledevice',
            index=models.Index(fields=['date', 'imei', 'device_name', 'longitude', 'latitude', 'gps_utc_time', 'send_time', 'protocol', 'record_date'], name='idle_time_date_991695_idx'),
        ),
    ]
