# Generated by Django 2.1.4 on 2019-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0023_auto_20190905_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obdmarkers',
            name='digital_status',
        ),
        migrations.AddField(
            model_name='obdmarkers',
            name='device_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
