# Generated by Django 2.1.4 on 2019-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0024_auto_20190920_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obdmarkers',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
