# Generated by Django 2.1.4 on 2019-10-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0025_auto_20191016_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obdmarkers',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
