# Generated by Django 2.1.4 on 2019-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0027_auto_20191016_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcrecords',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
