# Generated by Django 2.1.4 on 2019-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0028_dtcrecords_vin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarshAcceleration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=10, null=True)),
                ('count_number', models.CharField(blank=True, max_length=10, null=True)),
                ('imei', models.CharField(max_length=20)),
                ('report_type', models.CharField(blank=True, max_length=3, null=True)),
                ('data_status', models.IntegerField(null=True)),
                ('acceleration_x', models.FloatField(null=True)),
                ('acceleration_y', models.FloatField(null=True)),
                ('acceleration_z', models.FloatField(null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'harsh_acceleration',
            },
        ),
        migrations.AddIndex(
            model_name='harshacceleration',
            index=models.Index(fields=['date', 'imei', 'longitude', 'latitude', 'send_time', 'protocol', 'record_date'], name='harsh_accel_date_736e85_idx'),
        ),
    ]
