# Generated by Django 2.1.4 on 2019-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0029_auto_20191121_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignitiononoff',
            name='engine_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='engine_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='fuel_level_input',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiononoff',
            name='obd_power_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
