# Generated by Django 2.1.4 on 2020-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0033_auto_20200107_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFenceObd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol_version', models.CharField(blank=True, max_length=10, null=True)),
                ('imei', models.CharField(max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=15, null=True)),
                ('report_type', models.CharField(blank=True, max_length=3, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('gps_utc_time', models.CharField(blank=True, max_length=14, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('count_number', models.CharField(blank=True, max_length=10, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'geofence_obd',
            },
        ),
        migrations.AddIndex(
            model_name='geofenceobd',
            index=models.Index(fields=['date', 'imei', 'device_name', 'longitude', 'latitude', 'gps_utc_time', 'send_time', 'protocol', 'record_date'], name='geofence_ob_date_52f561_idx'),
        ),
    ]
