# Generated by Django 2.1.4 on 2021-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0036_enginesummary_trip_mileage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['send_time', 'imei', 'gps_accuracy'], name='gl_fri_mark_send_ti_e22c28_idx'),
        ),
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['longitude', 'latitude'], name='gl_fri_mark_longitu_1304e4_idx'),
        ),
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['send_time', 'imei', 'longitude', 'latitude', 'gps_accuracy'], name='gl_fri_mark_send_ti_01fb18_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['send_time', 'imei'], name='stt_markers_send_ti_61a891_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['longitude', 'latitude'], name='stt_markers_longitu_288a33_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['send_time', 'imei', 'longitude', 'latitude'], name='stt_markers_send_ti_8cbe52_idx'),
        ),
    ]
