# Generated by Django 2.1.4 on 2021-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0037_auto_20210428_0525'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['send_time', 'imei', 'gps_accuracy', 'record_date', 'report_name'], name='gl_fri_mark_send_ti_40069a_idx'),
        ),
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['imei', 'gps_accuracy', 'record_date', 'report_name'], name='gl_fri_mark_imei_7fcd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['send_time', 'imei'], name='gl_fri_mark_send_ti_71986e_idx'),
        ),
        migrations.AddIndex(
            model_name='glfrimarkers',
            index=models.Index(fields=['record_date', 'imei'], name='gl_fri_mark_record__2c08f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['record_date', 'imei'], name='stt_markers_record__3f76e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['report_name', 'imei'], name='stt_markers_report__a6d2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['imei'], name='stt_markers_imei_765dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='sttmarkers',
            index=models.Index(fields=['send_time'], name='stt_markers_send_ti_4ec43b_idx'),
        ),
    ]
