# Generated by Django 2.1.4 on 2021-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0039_auto_20210618_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obdtcrecords',
            name='count_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obdtcrecords',
            name='protocol',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='obdtcrecords',
            name='protocol_version',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='obdtcrecords',
            name='warning_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='obdtcrecords',
            name='warning_value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
